kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: managed-services-broker
  labels:
    app:  managed-services-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  managed-services-broker
  template:
    metadata:
      labels:
        app:  managed-services-broker
    spec:
      containers:
      - name: managed-services-broker
        image: dimitraz/managed-service-broker:1.0.0
        imagePullPolicy: Always
        args:
        - --port
        - "8080"
        # - --alsologtostderr
        # - --tlsCert
        # - "{{ .Values.tls.cert }}"
        # - --tlsKey
        # - "{{ .Values.tls.key }}"
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2