kind: Service
apiVersion: v1
metadata:
  name: managed-services-broker
  labels:
    app:  managed-services-broker
spec:
  selector:
    app:  managed-services-broker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080